var weapon_type = Weapon.UNARMED;
weapons[weapon_type] = ds_map_create();
ds_map_add(weapons[weapon_type], "sprite", noone);
ds_map_add(weapons[weapon_type], "recoil", 0);
ds_map_add(weapons[weapon_type], "recoil_push", 0);
ds_map_add(weapons[weapon_type], "damage", 1);
ds_map_add(weapons[weapon_type], "projectile", noone);
ds_map_add(weapons[weapon_type], "startup", -10);
ds_map_add(weapons[weapon_type], "length", -1);
ds_map_add(weapons[weapon_type], "cooldown", -1);
ds_map_add(weapons[weapon_type], "bulletspeed", -1);
ds_map_add(weapons[weapon_type], "automatic", false);
ds_map_add(weapons[weapon_type], "rank", Rank.D);

var weapon_type = Weapon.PISTOL;
weapons[weapon_type] = ds_map_create();
ds_map_add(weapons[weapon_type], "sprite", sGun);
ds_map_add(weapons[weapon_type], "recoil", 0);
ds_map_add(weapons[weapon_type], "recoil_push", 0);
ds_map_add(weapons[weapon_type], "damage", 1);
ds_map_add(weapons[weapon_type], "projectile", oBullet);
ds_map_add(weapons[weapon_type], "startup", 0);
ds_map_add(weapons[weapon_type], "length", 16);
ds_map_add(weapons[weapon_type], "cooldown", 1);
ds_map_add(weapons[weapon_type], "bulletspeed", 1);
ds_map_add(weapons[weapon_type], "automatic", false);
ds_map_add(weapons[weapon_type], "rank", Rank.C);

var weapon_type = Weapon.RIFLE;
weapons[weapon_type] = ds_map_create();
ds_map_add(weapons[weapon_type], "sprite", sRifle);
ds_map_add(weapons[weapon_type], "recoil", .7);
ds_map_add(weapons[weapon_type], "recoil_push", 0);
ds_map_add(weapons[weapon_type], "damage", 1);
ds_map_add(weapons[weapon_type], "projectile", oHitscan);
ds_map_add(weapons[weapon_type], "startup", 0);
ds_map_add(weapons[weapon_type], "length", 8);
ds_map_add(weapons[weapon_type], "cooldown", 5);
ds_map_add(weapons[weapon_type], "bulletspeed", 0);
ds_map_add(weapons[weapon_type], "automatic", true);
ds_map_add(weapons[weapon_type], "rank", Rank.C);

var weapon_type = Weapon.SHOTGUN;
weapons[weapon_type] = ds_map_create();
ds_map_add(weapons[weapon_type], "sprite", sShotgun);
ds_map_add(weapons[weapon_type], "recoil", 2);
ds_map_add(weapons[weapon_type], "recoil_push", 0);
ds_map_add(weapons[weapon_type], "damage", 1);
ds_map_add(weapons[weapon_type], "projectile", oHitscanShotgun);
ds_map_add(weapons[weapon_type], "startup", 0);
ds_map_add(weapons[weapon_type], "length", 8);
ds_map_add(weapons[weapon_type], "cooldown", 15);
ds_map_add(weapons[weapon_type], "bulletspeed", 0);
ds_map_add(weapons[weapon_type], "automatic", false);
ds_map_add(weapons[weapon_type], "rank", Rank.C);

var weapon_type = Weapon.SWORD;
weapons[weapon_type] = ds_map_create();
ds_map_add(weapons[weapon_type], "sprite", sSword);
ds_map_add(weapons[weapon_type], "recoil", 0);
ds_map_add(weapons[weapon_type], "recoil_push", 0);
ds_map_add(weapons[weapon_type], "damage", 1);
ds_map_add(weapons[weapon_type], "projectile", noone);
ds_map_add(weapons[weapon_type], "startup", 0);
ds_map_add(weapons[weapon_type], "length", 0);
ds_map_add(weapons[weapon_type], "cooldown", 1);
ds_map_add(weapons[weapon_type], "bulletspeed", 1);
ds_map_add(weapons[weapon_type], "automatic", false);
ds_map_add(weapons[weapon_type], "rank", Rank.C);
